### ISSUE TITLE
Parsing of negative declinations and latitudes

### ISSUE THREAD

**Issue by trishmapow** [OpenAstroTech/OpenAstroTracker-Desktop#25]
Just revisited this issue recently, but I'm not sure a straightforward fix is possible. The main issue is that the DEC components are stored individually, so there's no way of differentiating 0.xx and -0.xx. This means that any DEC value between 0 and -1 will always be buggy, even if it can be fixed for -1 to -90. To be clear, the issue is that for negative DEC/latitudes, the minute and second components should be subtracted, and not added to the degrees.

I'm not sure how you want to go forward with this, if maybe storing DEC degree as a string is OK, or some other solution. Personally I would prefer having a single entry field instead of three boxes, but perhaps that is too much work.

**Comment by ClutchplateDude** [comment]
This should no longer be an issue.
