### ISSUE TITLE
Feature Request: Stop button on mini window

### ISSUE THREAD

**Issue by DRA6N** [OpenAstroTech/OpenAstroTracker-Desktop#39]
![miniwindow_sample](https://user-images.githubusercontent.com/9896716/160193323-8c5855e4-9b0d-4de9-be66-08230dbc9e9d.jpg)

Add a "STOP" button to the mini window - see example photo. This is especially useful for someone like me that uses AHK to keep the mini window on top while running something like stellarium to control the slewing of the OAT. If for some reason the OAT runs into an issue and starts skipping the belt or something, the STOP button can be pressed to cease all movement of the OAT.

**Comment by DRA6N** [comment]
side-suggestion: Adding a "Stay On Top" toggle so you don't need an outside script like AHK :)

**Comment by ClutchplateDude** [comment]
> side-suggestion: Adding a "Stay On Top" toggle so you don't need an outside script like AHK :)

This is already implemented, albeit a little hidden. Right-click on the MiniControl button in the main screen and select Stay On Top

**Comment by DRA6N** [comment]
> > side-suggestion: Adding a "Stay On Top" toggle so you don't need an outside script like AHK :)
> 
> This is already implemented, albeit a little hidden. Right-click on the MiniControl button in the main screen and select Stay On Top

ah, yes! A little obfuscated but once you know, you know. I still like the idea of a stop button on the mini controller though :) Thanks

**Comment by ClutchplateDude** [comment]
That's why this issue is still
open 😁

**Comment by ClutchplateDude** [comment]
Added in V1.1.0.0
