### ISSUE TITLE
GPS Sync causing crashing

### ISSUE THREAD

**Issue by mathisfunzy** [OpenAstroTech/OpenAstroTracker-Desktop#5]
[Hello,]

Using OATControl v0.9.9.16 (also tried v0.9.9.15) with firmware v1.8.64 and ASCOM driver v0.3.0.0.  After successful connection on COM4, OATControl shows active GYRO, then upon successful GPS sync message ("SYNC'd.  Receiving current location") the app immediately crashes with no error message.  I am not sure where to investigate an error log.  However, I used the new OATComTester and it seems to show successful connection.  I have tried on two different PCs, same result.  I know the MEGA has GPS, as if I plug into power, it will sync with 7+ SATs and set the correct HA (indicated with blinking GPS).  

[OATControl_2021-01-24_17-05-41-mathi.log](https://github.com/OpenAstroTech/OpenAstroTracker-Desktop/files/5863421/OATControl_2021-01-24_17-05-41-mathi.log)

**Comment by christian-kardach** [comment]
was able to do repro, pending fix

**Comment by mathisfunzy** [comment]
Thank you for all the hard work and dedication.

**Comment by ClutchplateDude** [comment]
I think this is fixed. Please re-open if not.
